//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNettcpTest.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IProgramer")]
    public interface IProgramer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramer/WriteCode", ReplyAction="http://tempuri.org/IProgramer/WriteCodeResponse")]
        void WriteCode();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProgramerChannel : ConsoleNettcpTest.ServiceReference3.IProgramer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramerClient : System.ServiceModel.ClientBase<ConsoleNettcpTest.ServiceReference3.IProgramer>, ConsoleNettcpTest.ServiceReference3.IProgramer {
        
        public ProgramerClient() {
        }
        
        public ProgramerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteCode() {
            base.Channel.WriteCode();
        }
    }
}
