//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNettcpTest.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IDept")]
    public interface IDept {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDept/Add", ReplyAction="http://tempuri.org/IDept/AddResponse")]
        void Add();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeptChannel : ConsoleNettcpTest.ServiceReference2.IDept, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeptClient : System.ServiceModel.ClientBase<ConsoleNettcpTest.ServiceReference2.IDept>, ConsoleNettcpTest.ServiceReference2.IDept {
        
        public DeptClient() {
        }
        
        public DeptClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeptClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeptClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeptClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add() {
            base.Channel.Add();
        }
    }
}
